# Generated by Django 5.2.11 on 2026-02-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_subscription_status'),
        ('students', '0006_student_classroom_studentdocument_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('school', 'email')},
        ),
    ]
