# Generated by Django 5.2.11 on 2026-02-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_subscription_auto_renew_and_more'),
        ('teachers', '0005_teacherattendance_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('school', 'email'), ('school', 'employee_id')},
        ),
    ]
