# Generated by Django 5.2.11 on 2026-03-02 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0003_alter_subscription_status'),
        ('students', '0007_alter_parent_email_alter_parent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRiskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('risk_factors', models.JSONField()),
                ('ai_recommendations', models.TextField()),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='students.student')),
            ],
        ),
    ]
