# Generated by Django 5.2.11 on 2026-02-18 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_add_school_fields'),
        ('management', '0002_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='management.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='management.school'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='management.school'),
        ),
    ]
