# Generated by Django 5.2.11 on 2026-02-18 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classroom_school_alter_subject_school_and_more'),
        ('management', '0002_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarybook',
            name='isbn',
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='management.school'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='management.school'),
        ),
        migrations.AddField(
            model_name='librarybook',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_books', to='management.school'),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='management.school'),
        ),
    ]
