# Generated by Django 5.2.11 on 2026-02-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_librarybook_isbn_exam_school_and_more'),
        ('management', '0002_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'name', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
    ]
