# Generated by Django 5.2.11 on 2026-02-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_classroom_options_alter_subject_code_and_more'),
        ('management', '0003_alter_subscription_status'),
        ('students', '0007_alter_parent_email_alter_parent_unique_together'),
        ('teachers', '0006_alter_teacher_email_alter_teacher_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'exam', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='librarybook',
            unique_together={('school', 'title', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('classroom', 'day_of_week', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='transportroute',
            unique_together={('school', 'route_name')},
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classroom')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='management.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'classroom', 'subject')},
            },
        ),
    ]
