# Generated by Django 5.2.11 on 2026-02-24 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_examresult_unique_together_and_more'),
        ('management', '0003_alter_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('EXAM', 'Exam'), ('EXTRA', 'Extracurricular'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('target_audience', models.CharField(choices=[('ALL', 'All'), ('STAFF', 'Staff Only'), ('STUDENT', 'Students Only'), ('PARENT', 'Parents')], default='ALL', max_length=20)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='management.school')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
