# Generated by Django 5.2.11 on 2026-03-02 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_schoolevent'),
        ('management', '0003_alter_subscription_status'),
        ('students', '0007_alter_parent_email_alter_parent_unique_together'),
        ('teachers', '0007_staffleave_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='academics.classroom')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='management.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='teachers.teacher')),
            ],
            options={
                'verbose_name_plural': 'Gradebook Entries',
                'indexes': [models.Index(fields=['teacher', 'subject', 'classroom'], name='academics_g_teacher_f28595_idx'), models.Index(fields=['student', 'subject'], name='academics_g_student_ad1b45_idx')],
            },
        ),
    ]
