# Generated by Django 5.2.11 on 2026-02-18 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classroom_school_alter_subject_school_and_more'),
        ('finance', '0001_initial'),
        ('management', '0002_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='management.school'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='management.school'),
        ),
        migrations.AddField(
            model_name='feetype',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='management.school'),
        ),
    ]
