# Generated by Django 5.2.11 on 2026-02-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_feepayment_school_feestructure_classroom_and_more'),
        ('management', '0002_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feetype',
            unique_together={('school', 'name')},
        ),
    ]
