# Generated by Django 5.2.11 on 2026-02-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_examresult_unique_together_and_more'),
        ('finance', '0003_alter_feetype_unique_together'),
        ('management', '0003_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('school', 'fee_type', 'classroom', 'academic_year')},
        ),
    ]
