# Generated by Django 5.2.11 on 2026-03-06 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_feestructure_unique_together'),
        ('management', '0004_school_logo'),
        ('students', '0008_behaviorreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='grace_period_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='late_fine_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('fee_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='finance.feepayment')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='management.school')),
            ],
        ),
        migrations.CreateModel(
            name='RazorpayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=512, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='CREATED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fee_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='razorpay_order', to='finance.feepayment')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feestructure')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_orders', to='management.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_orders', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INITIATED', 'Initiated'), ('WEBHOOK_RECEIVED', 'Webhook Received'), ('VERIFIED', 'Verified'), ('PAYMENT_CREATED', 'Payment Record Created'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('SIGNATURE_MISMATCH', 'Signature Mismatch')], max_length=30)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('razorpay_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='finance.razorpayorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LateFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_overdue', models.IntegerField()),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_waived', models.BooleanField(default=False)),
                ('waive_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feestructure')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='late_fines', to='management.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_fines', to='students.student')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_fines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'is_waived'], name='finance_lat_school__f77645_idx')],
                'unique_together': {('student', 'fee_structure')},
            },
        ),
        migrations.AddIndex(
            model_name='razorpayorder',
            index=models.Index(fields=['razorpay_order_id'], name='finance_raz_razorpa_3a84a5_idx'),
        ),
        migrations.AddIndex(
            model_name='razorpayorder',
            index=models.Index(fields=['student', 'status'], name='finance_raz_student_b15306_idx'),
        ),
    ]
