# Generated by Django 5.2.11 on 2026-03-06 06:29

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_feestructure_grace_period_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereceipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=finance.models.upload_fee_receipt_pdf),
        ),
    ]
