#!/bin/bash
DB="sunrise_db"

echo "Creating Celery Beat tables in $DB..."

sudo -u postgres psql -d $DB -c '
CREATE TABLE IF NOT EXISTS "django_celery_beat_clockedschedule" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "clocked_time" timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS "django_celery_beat_crontabschedule" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "minute" varchar(240) NOT NULL, "hour" varchar(240) NOT NULL, "day_of_week" varchar(240) NOT NULL, "day_of_month" varchar(240) NOT NULL, "month_of_year" varchar(240) NOT NULL, "timezone" varchar(63) NOT NULL);
CREATE TABLE IF NOT EXISTS "django_celery_beat_intervalschedule" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "every" integer NOT NULL, "period" varchar(24) NOT NULL);
CREATE TABLE IF NOT EXISTS "django_celery_beat_solarschedule" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "event" varchar(24) NOT NULL, "latitude" numeric(9, 6) NOT NULL, "longitude" numeric(9, 6) NOT NULL);
CREATE TABLE IF NOT EXISTS "django_celery_beat_periodictasks" ("ident" smallint NOT NULL PRIMARY KEY, "last_update" timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS "django_celery_beat_periodictask" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL UNIQUE, "task" varchar(200) NOT NULL, "args" text NOT NULL, "kwargs" text NOT NULL, "queue" varchar(200) NULL, "exchange" varchar(200) NULL, "routing_key" varchar(200) NULL, "expires" timestamp with time zone NULL, "enabled" boolean NOT NULL, "last_run_at" timestamp with time zone NULL, "total_run_count" integer NOT NULL, "date_changed" timestamp with time zone NOT NULL, "description" text NOT NULL, "crontab_id" bigint NULL, "interval_id" bigint NULL, "solar_id" bigint NULL, "clocked_id" bigint NULL, "one_off" boolean NOT NULL, "start_time" timestamp with time zone NULL, "priority" integer NULL, "headers" text NOT NULL, "expire_seconds" integer NULL);
'

echo "DONE"
