#!/bin/bash
DB="sunrise_db"

echo "Applying manual migrations to $DB..."

# 1. StudentAttendance
sudo -u postgres psql -d $DB -c '
CREATE TABLE IF NOT EXISTS "students_studentattendance" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "date" date NOT NULL, 
    "status" varchar(10) NOT NULL, 
    "remarks" text NULL, 
    "school_id" bigint NULL, 
    "student_id" bigint NOT NULL
);
ALTER TABLE "students_studentattendance" DROP CONSTRAINT IF EXISTS "students_studentattendance_student_id_date_bf4aea24_uniq";
ALTER TABLE "students_studentattendance" ADD CONSTRAINT "students_studentattendance_student_id_date_bf4aea24_uniq" UNIQUE ("student_id", "date");
'

# 2. TeacherAttendance
sudo -u postgres psql -d $DB -c '
CREATE TABLE IF NOT EXISTS "teachers_teacherattendance" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "date" date NOT NULL, 
    "status" varchar(10) NOT NULL, 
    "remarks" text NULL, 
    "school_id" bigint NULL, 
    "teacher_id" bigint NOT NULL
);
ALTER TABLE "teachers_teacherattendance" DROP CONSTRAINT IF EXISTS "teachers_teacherattendance_teacher_id_date_key";
ALTER TABLE "teachers_teacherattendance" ADD CONSTRAINT "teachers_teacherattendance_teacher_id_date_key" UNIQUE ("teacher_id", "date");
'

# 3. StaffLeave
sudo -u postgres psql -d $DB -c '
CREATE TABLE IF NOT EXISTS "teachers_staffleave" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "start_date" date NOT NULL, 
    "end_date" date NOT NULL, 
    "reason" text NOT NULL, 
    "status" varchar(20) NOT NULL, 
    "applied_on" timestamp with time zone NOT NULL, 
    "reviewed_on" timestamp with time zone NULL, 
    "admin_remarks" text NULL, 
    "school_id" bigint NULL, 
    "teacher_id" bigint NOT NULL
);
'

# 4. Payroll
sudo -u postgres psql -d $DB -c '
CREATE TABLE IF NOT EXISTS "teachers_payroll" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "month" date NOT NULL, 
    "base_salary" numeric(10, 2) NOT NULL, 
    "deductions" numeric(10, 2) NOT NULL, 
    "net_payable" numeric(10, 2) NOT NULL, 
    "status" varchar(20) NOT NULL, 
    "paid_on" date NULL, 
    "school_id" bigint NULL, 
    "teacher_id" bigint NOT NULL
);
ALTER TABLE "teachers_payroll" DROP CONSTRAINT IF EXISTS "teachers_payroll_teacher_id_month_key";
ALTER TABLE "teachers_payroll" ADD CONSTRAINT "teachers_payroll_teacher_id_month_key" UNIQUE ("teacher_id", "month");
'

echo "Done manual migration."
