# Generated by Django 5.2.11 on 2026-03-06 06:09

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=management.models.upload_school_logo),
        ),
    ]
