# Generated by Django 5.2.11 on 2026-03-02 09:43

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.TenantUserManager()),
            ],
        ),
    ]
