"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import environ
from datetime import timedelta
from pathlib import Path

# Initialize environ
env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['*', 'backend.local', 'frontend.local', '192.168.1.23', '192.168.1.145', 'localhost']

SCHOOL_NAME = 'Sunrise Public School'


# Application definition

INSTALLED_APPS = [
    'jazzmin',              # Must be BEFORE django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'django_filters',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'analytics_ai',
    
    # Internal apps
    'management',
    'users',
    'students',
    'teachers',
    'finance',
    'academics',
    'notifications',
    'analytics',
    'messaging',
    
    # Task Scheduling
    'django_celery_beat',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Put CORS at the top
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Custom Middleware for Tenant Routing
    'core.middleware.TenantMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default='postgres://satyam:satyam@127.0.0.1:5432/sms_central_db'),
}

# Ensure transaction pooling compatibility (PgBouncer)
for db in DATABASES.values():
    db['CONN_MAX_AGE'] = 0

# Tenant DB Configuration (Exposed for Middleware)
TENANT_DB_USER = env('TENANT_DB_USER', default='satyam')
TENANT_DB_PASSWORD = env('TENANT_DB_PASSWORD', default='satyam')
TENANT_DB_HOST = env('TENANT_DB_HOST', default='127.0.0.1')
TENANT_DB_PORT = env('TENANT_DB_PORT', default='5432')

# Add dynamic tenant DB support for management commands
import sys
if 'migrate' in sys.argv:
    # Try to get database from --database argument
    db_index = -1
    for i, arg in enumerate(sys.argv):
        if arg.startswith('--database='):
            db_name = arg.split('=')[1]
            if db_name != 'default':
                DATABASES[db_name] = {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': db_name,
                    'USER': TENANT_DB_USER,
                    'PASSWORD': TENANT_DB_PASSWORD,
                    'HOST': TENANT_DB_HOST,
                    'PORT': TENANT_DB_PORT,
                    'CONN_MAX_AGE': 0,
                }
        elif arg == '--database' and i + 1 < len(sys.argv):
            db_name = sys.argv[i+1]
            if db_name != 'default':
                DATABASES[db_name] = {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': db_name,
                    'USER': TENANT_DB_USER,
                    'PASSWORD': TENANT_DB_PASSWORD,
                    'HOST': TENANT_DB_HOST,
                    'PORT': TENANT_DB_PORT,
                    'CONN_MAX_AGE': 0,
                }

# Database Router for Multi-Tenancy
DATABASE_ROUTERS = ['core.db_router.TenantRouter']

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.CookieJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Enables DRF browsable API login
        'rest_framework.authentication.BasicAuthentication',   # Fallback for browser testing
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'login': '5/min',
    },
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Cookie Settings for JWT
AUTH_COOKIE = 'access_token'
AUTH_COOKIE_REFRESH = 'refresh_token'
AUTH_COOKIE_DOMAIN = None
AUTH_COOKIE_SECURE = not DEBUG
AUTH_COOKIE_HTTP_ONLY = True
AUTH_COOKIE_PATH = '/'
AUTH_COOKIE_SAMESITE = 'Lax'

# CORS Settings
CORS_ALLOW_CREDENTIALS = True

# In production, we strictly whitelist origins.
# For local development (DEBUG=True), we can be more permissive.
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
    # Support for tenant subdomains (e.g., school1.smsapp.com)
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^https://[a-zA-Z0-9-]+\.smsapp\.com$", # Replace smsapp.com with actual production domain
    ]

# CSRF Settings
CSRF_COOKIE_HTTPONLY = False # Must be False for JS to read if needed, but we'll use header
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'http://192.168.1.23:3000',
    'http://192.168.1.23:3001',
    'http://192.168.1.23:8000',
    'http://192.168.1.145:3000',
    'http://192.168.1.145:3001',
    'http://192.168.1.145:8000',
    'http://localhost:8000',
    'http://frontend.local:3000',
    'http://frontend.local:3001',
    'http://backend.local:8000',
])

USE_S3 = bool(os.getenv('DJANGO_USE_S3'))

# AWS
if USE_S3:
    # https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_S3_MAX_MEMORY_SIZE = 10  # roll over to temporary file on disk if over limit
    AWS_ACCESS_KEY_ID = os.getenv('DJANGO_S3_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('DJANGO_S3_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('DJANGO_S3_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('DJANGO_S3_REGION', 'ap-south-1')
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_CUSTOM_DOMAIN = os.getenv('DJANGO_S3_CUSTOM_DOMAIN')
    AWS_QUERYSTRING_AUTH = False
    AWS_DEFAULT_ACL = os.getenv('AWS_DEFAULT_ACL')
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_VERIFY = True
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    }
}


# Celery Configuration
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Razorpay Configuration
RAZORPAY_KEY_ID = env('RAZORPAY_KEY_ID', default='rzp_test_placeholder')
RAZORPAY_KEY_SECRET = env('RAZORPAY_KEY_SECRET', default='rzp_secret_placeholder')

# Email Configuration
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env('EMAIL_PORT', cast=int, default=587)
EMAIL_USE_TLS = env('EMAIL_USE_TLS', cast=bool, default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=f"{SCHOOL_NAME} <noreply@example.com>")

# ─────────────────────────────────────────────────────────────────────────────
# Jazzmin Admin UI Settings
# ─────────────────────────────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    # ── Branding ──────────────────────────────────────────────────────────────
    'site_title': 'SMS Admin',
    'site_header': 'School Management System',
    'site_brand': 'SMS',
    'welcome_sign': 'Welcome to the School Management System',
    'copyright': 'Sunrise Public School',

    # ── Top-bar search ─────────────────────────────────────────────────────
    'search_model': ['users.User', 'students.Student', 'teachers.Teacher'],

    # ── User avatar / account menu ─────────────────────────────────────────
    'user_avatar': None,

    # ── Top-right links ────────────────────────────────────────────────────
    'topmenu_links': [
        {'name': 'Home', 'url': 'admin:index', 'permissions': ['auth.view_user']},
        {'name': 'Site', 'url': '/', 'new_window': True},
    ],

    # ── Sidebar user-menu links ────────────────────────────────────────────
    'usermenu_links': [
        {'name': 'Support', 'url': 'https://github.com/farridav/django-jazzmin/issues', 'new_window': True},
        {'model': 'auth.user'},
    ],

    # ── Sidebar ────────────────────────────────────────────────────────────
    'show_sidebar': True,
    'navigation_expanded': True,
    'hide_apps': [],
    'hide_models': [],

    # Display app list in sidebar with custom icons
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'users.User': 'fas fa-user-circle',
        'students.Student': 'fas fa-user-graduate',
        'students.Parent': 'fas fa-user-friends',
        'teachers.Teacher': 'fas fa-chalkboard-teacher',
        'academics.Classroom': 'fas fa-school',
        'academics.Subject': 'fas fa-book',
        'academics.TeacherAssignment': 'fas fa-user-tag',
        'finance.FeeStructure': 'fas fa-money-bill-wave',
        'finance.Payment': 'fas fa-credit-card',
        'notifications.Notification': 'fas fa-bell',
        'analytics.Report': 'fas fa-chart-bar',
        'management.School': 'fas fa-building',
        'django_celery_beat.PeriodicTask': 'fas fa-clock',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',

    # ── Misc ───────────────────────────────────────────────────────────────
    'related_modal_active': True,
    'custom_css': None,
    'custom_js': None,
    'use_google_fonts_cdn': True,
    'show_ui_builder': False,
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': 'navbar-primary',
    'accent': 'accent-primary',
    'navbar': 'navbar-dark',
    'no_navbar_border': False,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': False,
    'theme': 'default',
    'dark_mode_theme': None,
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}
# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_RETRY_DELAY = 10     # 10 seconds

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://localhost:6379/2'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Custom domain lookup cache settings
DOMAIN_CACHE_TIMEOUT = 60 * 60  # 1 hour
